version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ask_pupkin_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ask_pupkin
      POSTGRES_USER: ask_pupkin
      POSTGRES_PASSWORD: ask_pupkin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
